/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import Hilos.Controla;
import Hilos.MATRIZ;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author andre
 */
public  class Pantalla_principal extends javax.swing.JFrame {

    public Pantalla_principal() {
        initComponents();
    }
    
   MATRIZ mat=new MATRIZ();
   Controla h1,h2,h3;
    private Timer t;
   Controla ctr=new Controla(mat);
    private boolean Col1=false,Col2=false,Col3=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        In1 = new javax.swing.JButton();
        P1 = new javax.swing.JButton();
        In2 = new javax.swing.JButton();
        P2 = new javax.swing.JButton();
        In3 = new javax.swing.JButton();
        P3 = new javax.swing.JButton();
        INICIAR = new javax.swing.JButton();
        PT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel1.setText("TIEMPO");

        In1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        In1.setText("INICIAR");
        In1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In1ActionPerformed(evt);
            }
        });

        P1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        P1.setText("PARAR");
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        In2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        In2.setText("INICIAR");
        In2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In2ActionPerformed(evt);
            }
        });

        P2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        P2.setText("PARAR");
        P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ActionPerformed(evt);
            }
        });

        In3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        In3.setText("INICIAR");
        In3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In3ActionPerformed(evt);
            }
        });

        P3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        P3.setText("PARAR");
        P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ActionPerformed(evt);
            }
        });

        INICIAR.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        INICIAR.setText("INICIAR");
        INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARActionPerformed(evt);
            }
        });

        PT.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        PT.setText("FINALIZAR");
        PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen1.png")));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen1.png")));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen1.png")));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen2.png")));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen2.png")));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen2.png")));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen3.png")));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen3.png")));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen3.png")));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen4.png")));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen4.png")));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes1/Imagen4.png")));

        jSpinner1.setToolTipText("");

        jTextField1.setBackground(new java.awt.Color(255, 0, 0));

        jTextField2.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(P1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(In1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jSpinner1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(In2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(P2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSpinner2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(In3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(INICIAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PT))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INICIAR)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PT)
                            .addComponent(In1)
                            .addComponent(In2)
                            .addComponent(In3))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1)
                    .addComponent(P2)
                    .addComponent(P3))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARActionPerformed
        In1ActionPerformed(evt);
        In2ActionPerformed(evt);
        In3ActionPerformed(evt);
    }//GEN-LAST:event_INICIARActionPerformed

    private void In1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In1ActionPerformed
        if (Col1==false){
       Col1=true;
       int t1=(int)jSpinner1.getValue();
       if (t1<=0)  {
           Col1=false;
           JOptionPane.showMessageDialog(null,"INGRESE UN VALOR A LA CASILLA");
       }else{
           h1=new Controla(mat,0,t1);
          h1.start();         
       }
       
        }else{
            JOptionPane.showMessageDialog(null, " YA SE ESTA EJECUTANDO LA COLUMNA");
        }
   
     


        
    }//GEN-LAST:event_In1ActionPerformed

    private void In2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In2ActionPerformed
     if (Col2==false){
         Col2=true;
         int t2=(int)jSpinner2.getValue();
        if (t2<=0)  {
            Col2=false;
           JOptionPane.showMessageDialog(null,"INGRESE UN VALOR A LA CASILLA");
       }else{
        h2=new Controla(mat,1,t2);
        h2.start();
         }
     }else{
            JOptionPane.showMessageDialog(null, " YA SE ESTA EJECUTANDO LA COLUMNA");
     }
        
    }//GEN-LAST:event_In2ActionPerformed

    private void In3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In3ActionPerformed
   if (Col3==false){
             Col3=true;
             int t3=(int)jSpinner3.getValue(); 
         if (t3<=0)  {
            Col3=false;
           JOptionPane.showMessageDialog(null,"INGRESE UN VALOR A LA CASILLA");
       }else{
              h3=new Controla(mat,2,t3);
            h3.start();   
         }
   }else{
            JOptionPane.showMessageDialog(null, " YA SE ESTA EJECUTANDO LA COLUMNA");
   }
  
     
        
    }//GEN-LAST:event_In3ActionPerformed

    private void PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTActionPerformed
        interrumpir(evt);
        ctr.verifica();
    }//GEN-LAST:event_PTActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        Col1=false;
        interrumpir(evt);
        int a[][];
        a=ctr.verifica2();
        a= ctr.verifica2();

    }//GEN-LAST:event_P1ActionPerformed

    private void P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ActionPerformed
         Col2=false;
        interrumpir(evt);
       int a[][];
       a= ctr.verifica2();
       Col2=false;
       
    }//GEN-LAST:event_P2ActionPerformed

    private void P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ActionPerformed
       Col3=false; 
        interrumpir(evt);
        int a[][];
        a= ctr.verifica2();
        Col3=false;
    }//GEN-LAST:event_P3ActionPerformed

 public static void cont(){
     
 }
    
public void interrumpir(ActionEvent evt){ 

    try{
        if(evt.getSource().equals(P1))
        {
            h1.interrupt();
            Col1=false;
        }
        if (evt.getSource().equals(P2))
        {
            h2.interrupt();
            Col2=false;
        }
        if (evt.getSource().equals(P3))
        {
            h3.interrupt();
            Col3=false;
        }
        if (evt.getSource().equals(PT))
        {
            h1.interrupt();
            h2.interrupt();
            h3.interrupt();
            Col1=false;
            Col2=false;
            Col3=false;
        }
        }catch(Exception ex) {
                
       }
    }

   static Icon icono0=new ImageIcon(Pantalla_principal.class.getResource("/Imagenes1/Imagen1.png"));
   static Icon icono1=new ImageIcon(Pantalla_principal.class.getResource("/Imagenes1/Imagen2.png"));
   static Icon icono2=new ImageIcon(Pantalla_principal.class.getResource("/Imagenes1/Imagen3.png"));
   static Icon icono3=new ImageIcon(Pantalla_principal.class.getResource("/Imagenes1/Imagen4.png"));
   static Icon aux;
public static void cambiamos(int c, int[][] pk){
    int val0=pk[0][c];
    int val1=pk[1][c];
    int val2=pk[2][c];
    int val3=pk[3][c];
    
    if (c==0){
        jLabel2.setIcon(imagen(val0));
        jLabel5.setIcon(imagen(val1));
        jLabel8.setIcon(imagen(val2));
        jLabel11.setIcon(imagen(val3));
    }
    if  (c==1){
       jLabel3.setIcon(imagen(val0));
        jLabel6.setIcon(imagen(val1));
        jLabel9.setIcon(imagen(val2));
        jLabel12.setIcon(imagen(val3));
    }
    if (c==2){
        jLabel4.setIcon(imagen(val0));
        jLabel7.setIcon(imagen(val1));
        jLabel10.setIcon(imagen(val2));
        jLabel13.setIcon(imagen(val3));
    }
}
public static Icon imagen(int llega){
    if (llega==0){
        return icono0;
    }
    if (llega==1){
      return icono1;
    }
    if (llega==2){
        return icono2;
    }
    if (llega==3){
      return icono3;
    }
    return null;
}

public static void  setear1(){
         aux= jLabel11.getIcon();
           jLabel11.setIcon(jLabel8.getIcon());
           jLabel8.setIcon(jLabel5.getIcon());
          jLabel5.setIcon(jLabel2.getIcon());
          jLabel2.setIcon(aux);
}
public static void  setear2(){
           aux= jLabel12.getIcon();
           jLabel12.setIcon(jLabel9.getIcon());
           jLabel9.setIcon(jLabel6.getIcon());
          jLabel6.setIcon(jLabel3.getIcon());
          jLabel3.setIcon(aux);
}
public static void  setear3(){
           aux= jLabel13.getIcon();
           jLabel13.setIcon(jLabel10.getIcon());
           jLabel10.setIcon(jLabel7.getIcon());
          jLabel7.setIcon(jLabel4.getIcon());
          jLabel4.setIcon(aux);
}




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INICIAR;
    private javax.swing.JButton In1;
    private javax.swing.JButton In2;
    private javax.swing.JButton In3;
    private javax.swing.JButton P1;
    private javax.swing.JButton P2;
    private javax.swing.JButton P3;
    private javax.swing.JButton PT;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel10;
    private static javax.swing.JLabel jLabel11;
    private static javax.swing.JLabel jLabel12;
    private static javax.swing.JLabel jLabel13;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel8;
    private static javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
